resources:
  - ../../base

namespace: iris

configMapGenerator:
  - name: iris-write-api-configs
    envs:
      - params.env
secretGenerator:
  - name: iris-write-api-secrets
    envs:
      - secrets.env

patches:
  - path: patches/gateway.yaml
    target:
      kind: Gateway
  - path: patches/allow-ingress-to-write-api.yaml
    target:
      kind: AuthorizationPolicy


labels:
  - pairs:
      env: demo


images:
  - name: iris-write-api-image
    newName: 503561419905.dkr.ecr.eu-west-2.amazonaws.com/iris/write-api
    newTag: '1736464040'


