name: Test feature branch
on:
  push:
    branches-ignore:
      - "main"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest ruff
          pip install -r requirements.txt
      - name: Lint with ruff
        run: |
          # stop the build if there are Python syntax errors or undefined names
          ruff --select=E9,F63,F7,F82 --target-version=py311 .
          # default set of ruff rules with GitHub Annotations - print only!
          ruff --target-version=py311 --exit-zero --quiet .
      # No tests yet
      # - name: Unit Tests
      #   run: |
      #     python3 -m unittest discover -s src --verbose